# Generated by Django 3.2 on 2021-04-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fistname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
                ('salary', models.FloatField()),
                ('mobile', models.BigIntegerField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
