# Generated by Django 3.2 on 2021-04-12 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Faker_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='fistname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
